name: daemon
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.1.0
  logging: ^1.2.0
  collection: ^1.17.1
  shelf_proxy: ^1.0.4
  shelf: ^1.4.1
  socks5_proxy: ^1.0.3+dev.3
  path: ^1.8.3
  meta: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
