@startuml
skinparam componentStyle uml2

skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

[GUI]
[CLI]
[DAEMON]
[MONITOR_PROCESS]
[HELPERS]

[GUI] - [CLI]

[HELPERS] .down.> [encrypt_data]
[HELPERS] .down.> [decrypt_data]
[HELPERS] .down.> [check_for_block]
[HELPERS] .down.> [cheater_popup]
[HELPERS] .down.> [soft_block_popup]
[HELPERS] .down.> [consume_config]
[HELPERS] .down.> [end_block]
[HELPERS] .down.> [integrity_fix]

[check_for_block] .up.> [decrypt_data]


[end_block] .up.> [check_for_block]
[end_block] .up.> [deactivate_hosts_block]
[end_block] .down.> [deactivate_pf_block]
[end_block] .down.> [deactivate_windows_firewall_block]
[deactivate_pf_block] .down.> [stop_macos_daemon]
[deactivate_windows_firewall_block] .down.> [stop_windows_daemon]
[stop_macos_daemon] .down.> [deactivate_block_in_config]
[stop_windows_daemon] .down.> [deactivate_block_in_config]
[deactivate_block_in_config] .up.> [encrypt_data]



[CLI] .down.> [init]
[CLI] .down.> [manage_blocklist]
[CLI] .down.> [manage_block]
[CLI] .down.> [integrity_fix]
[CLI] .down.> [show_popup]

[init] .down.> [check_for_config]
[check_for_config] .down.> [create_config]
[create_config] .down.> [activate_tutorial]


[manage_blocklist] .up.> [check_for_block]
[manage_blocklist] .down.> [get_blocklists]
[manage_blocklist] .down.> [add_blocklist]
[manage_blocklist] .down.> [remove_blocklist]
[manage_blocklist] .down.> [edit_blocklist]

[get_blocklists] .up.> [decrypt_data]
[add_blocklist] .up.> [encrypt_data]
[edit_blocklist] .up.> [encrypt_data]


[manage_block] .up.> [check_for_block]
[manage_block] .down.> [start_block]
[manage_block] .down.> [end_block]

[start_block] .up.> [decrypt_data]
[start_block] .down.> [activate_hosts_block]
[start_block] .down.> [activate_pf_block]
[start_block] .down.> [activate_windows_firewall_block]

[activate_pf_block] .down.> [generate_daemon_plist]
[activate_windows_firewall_block] .down.> [start_windows_daemon]

[generate_daemon_plist] .down.> [start_macos_daemon]
[start_macos_daemon] .down.> [activate_block_in_config]
[start_windows_daemon] .down.> [activate_block_in_config]

[activate_block_in_config] .up.> [encrypt_data]


[integrity_fix] .down.> [init]
[integrity_fix] .up.> [cheater_popup]
[integrity_fix] .down.> [end_block]
[integrity_fix] .down.> [start_block]



[DAEMON] .up.> [MONITOR_PROCESS]
[DAEMON] .up.> [consume_config]
[DAEMON] .down.> [activate_file_watchers]
[activate_file_watchers] .down.> [integrity_fix]
[activate_file_watchers] .up.> [decrypt_data]

[activate_file_watchers] .down.> [activate_countdown]
[activate_countdown] .down.> [end_block]

[activate_file_watchers] .down.> [activate_app_blocker]
[activate_app_blocker] .up.> [soft_block_popup]

[activate_file_watchers] .down.> [activate_website_softblock]
[activate_website_softblock] .down.> [activate_hosts_softblock]
[activate_hosts_softblock] .up.> [soft_block_popup]
[activate_website_softblock] .down.> [deactivate_hosts_softblock]

[MONITOR_PROCESS] .up.> [consume_config]
[MONITOR_PROCESS] .down.> [daemon_watcher]
[daemon_watcher] .down.> [restore_daemon]

@enduml
